#!/bin/bash
# Really simple screen recorder
#
# Usage: 
#       Run the script from a terminal and click on a window.
#       Hit 'q' in the terminal when done.
#
# To record the root window, click on the root window.
# Hitting ^C during recording will remove the dst file.
#
# Tweaks: See the fps variable, or the bottom line 
#         where ffmpeg is executed.
#
# Copyright (C) 2010-2013 Kristian Gunstone
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

fps=20

deps=(ffmpeg xwininfo grep cut awk sed basename mktemp)

# Dependency checking
count=0

for dep in ${deps[*]}; do
	if [ ! $(which $dep) ]; then
		echo "Missing dependency: $dep";
		((count++))
	fi
done

if [ $count -ne 0 ]; then
	echo "$count dependencies not met."
	exit 1
fi

unset count

name=$(basename $0)
name=${name//[^aA-zZ]/}
tmp=$(mktemp -t "$name-XXXXX.tmp")
unset name

echo -e "\nClick on the desired window. Its initial geometry is the area being captured.\n"
echo "'q' quits and prints the dst file."
echo "^C will CANCEL and REMOVE the dst."

# Run xwininfo to grab window
xwininfo > $tmp

# Grab id and name (Although we don't need id anymore!)
idname=$(grep "Window id" $tmp | cut -d : -f 3)
id=$(echo $idname | awk '{print $1}')
name=$(echo $idname | awk '{print $2}' | tr -d \")
unset idname

# Grab width, height
 width=$(grep "Width:" $tmp | awk '{print $2}')
height=$(grep "Height:" $tmp | awk '{print $2}')

# Grab offsets
offsx=$(grep "Absolute upper-left X:" ${tmp} | awk '{print $4}')
offsy=$(grep "Absolute upper-left Y:" ${tmp} | awk '{print $4}')

rm -f $tmp

dims=${width}x${height}

echo -e "\nGeometry for \"${name}\" (${id}) is ${dims}+${offsx}+${offsy}."

name=${name//[^aA-zZ]/_}
dst=$(mktemp -u $name-XXXX.mkv)

echo -e "Launching ffmpeg.\n"

# See http://ffmpeg.org/trac/ffmpeg/wiki/x264EncodingGuide for encoding specifics
ffmpeg -loglevel panic \
       -f x11grab \
       -r $fps \
       -s $dims \
       -i :0.0+${offsx},${offsy} \
       -vcodec libx264 \
       -preset ultrafast \
       -crf 0 \
       -threads 0 \
       $dst \
&& {
	echo -e "\nFinished:" 
	du -sh "$dst"
} || { 
	rm -f $dst
}
