#!/bin/bash
# A really simple but versatile screenshot generator which produces neat, 
# sequentially named files.
#
# Copyright (C) 2012 Kristian Gunstone
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

    dst=$(pwd)
 prefix="screenshot"
timefmt="-%y%m%d-"
 numfmt="%03d"
postfix=
 suffix="jpg"

timestr=$(date +"$timefmt")

usage() {
	echo -e "Simple but versatile screenshot generator\n"
	echo "Usage: $(basename $0) [options]"
	echo -e "Example: $(basename $0) -d ~ -e png \n"
	echo "-d <dst>      set destination path   (default: \$(pwd))"
	echo "-p <prefix>   set prefix             (default: \"$prefix\")"
	echo "-t <timefmt>  set time format        (default: \"$timefmt\")"
	echo "-P <postfix>  set postfix            (default: \"$postfix\")"
	echo "-n <numfmt>   set number format      (default: \"$numfmt\")"
	echo "-s <suffix>   set suffix             (default: \"$suffix\")"
	echo -e "\nOutput file will be <dst>/<prefix><timefmt><num><postfix>.<suffix>, eg"

	printf "%s/%s%s$numfmt%s.%s\n\n" \
	       "$dst" "$prefix" "$timestr" 1 "$postfix" "$suffix"
}

while [ $# -gt 0 ]; do 
	case "$1" in
		-d) dst="$2";;
		-p) prefix="$2";;
		-t) timefmt="$2";;
		-P) postfix="$2";;
		-n) numfmt="$2";;
		-s) suffix="$2";;
		-h) usage
		    exit 0;;
	esac
	shift
done
	
beg=$(printf "%s/%s%s" "$dst" "$prefix" "$timestr")

let num=(1 + $(ls "$beg"*"$postfix.$suffix" 2>/dev/null | wc -l))

out=$(printf "%s$numfmt%s.%s" "$beg" $num "$postfix" "$suffix")

imlib2_grab "$out" || import -window root "$out" && {
	echo "Saved \"$out\""
	xmessage -timeout 2 -buttons "" -center "Saved \"$out\"" > /dev/null 2>&1
} || {
	ret=$?
	echo "Boo, failed to take screenshot."
	exit $ret
}
