#!/bin/bash
# Automatically concatenate split files using only the original
# filename and an index. Ie 
# `file_cat foo.mp4 1` concatenates 
# foo.mp4.001
# foo.mp4.002
# foo.mp4.003
# into
# foo.mp4

delimiter='.'
   filter="\\$delimiter[0-9]*\$"
    index=1
       in="$1"

if [ $# -lt 1 ]; then
	m="$(basename $0)"
	echo "Usage: $m <file prefix> [offset]"
	echo "Example: $m foo.mp4 0"
	exit 0
fi

[ ! -z $2 ] && index=$2


if [ -e "$in" ]; then
	echo "\"$in\" already exists."
	exit 0
fi

       cmd='ls "$in"* | grep -e "'$filter'"'
file_count=$(eval $cmd | wc -l)

[ $file_count = 0 ] && exit 1

      file_last=$(eval $cmd | tail -n1 | awk -F "$delimiter" '{print $NF}') 
file_last_index=$(expr "$file_last" + 0) # Zero-pad the string (083->83)
      pad_count=${#file_last}

if [ $file_count -ne $file_last ]; then
	echo "Error: File count doesn't match last index: $file_count files," \
	     "but last file index is $file_last_index" >2
	exit 1
fi

echo -e "Concatenating ${in}.{${index}..${file_last}}\n"

for (( x=$index; x <= $file_last_index; x++ )); do
	src=$(printf "%s.%0${pad_count}d" "$in" $x)
	printf "%s >> %s %${pad_count}d/%s\n" "$src" "$in" $x $file_last_index
	cat "$src" >> "$in"
done
