#!/bin/bash

screen_launch() {
	echo "$1 -> [$name]"
	shift

	screen $@
	ret=$?

	if [ $ret -ne 0 ]; then
		echo -ne "Error: screen terminated unexpectedly ($ret): "
	        echo "exiting without cleanup."
		exit $ret
	fi
}

if [ $# -lt 2 ]; then
	n=$(basename $0)
	echo -ne "\nCreate a screen and add one or more windows to it in a "
	echo -e "detached state\n"
	echo "Usage: $n <screen name> \"<command>\" [\"command\"] [...]"
	echo -e "Example: $n services \"watch ls\" \"tail -f /var/log/\"\n"
	exit 0
fi

name=$1
shift

if ! $(screen -ls $name | grep "No Sockets" > /dev/null 2>&1); then
	echo -n "Fatal: Screen with name \"$name\" already exists. "
	echo "I'd better not add windows to it:"
	screen -ls $name
	exit 1
fi

screen_launch "$1" -S $name -d -m $1

shift

for c in "$@"; do
	screen_launch "$c" -dr $name -X screen $c
done
