#!/bin/bash
# A quick and dirty thumbnailer which uses 'convert'to do the job. By gammy.

src=""
dst="thumbs"
prefix="thumb_"
convert="convert"

usage() {
	echo -e "Quick n dirty thumbnailer\n"
	echo "Usage: $(basename $0) -s <source path> [options] <convert args>"
	echo -e "Example: $(basename $0) -p thumb_ -s /originals/ -d ./thumbs/ -- -size 100x100\n"
	echo "-s foo     set source path to 'foo'"
	echo "-d ${dst}  set destination path to '${dst}'"
	echo -e "-P ${prefix}  set target prefix to '${prefix}'\n"
	echo "Only the -s argument is required to run."
}

while getopts “s:d:s:p:h” opt; do
	case $opt in
		s)
			src="$OPTARG"
			;;
		d)
			dst="$OPTARG"
			;;
		p)
			prefix="${OPTARG}"
			;;
		h)
			usage
			exit 1
			;;
	esac
done

if [ -z ${src} ]; then
	usage
	exit 1
fi

if [ $(which "${convert}" | wc -l)  = 0 ]; then
	echo "Can't find command \"${convert}\""
	exit 0
fi

if [ ! -d ${dst} ]; then
	mkdir -v ${dst}
fi

find ${src} -maxdepth 1 -type f | while read old; do

	if [ $(file "${old}" | grep image | wc -l) != 1 ]; then
		continue 
	fi

	type=${old##*.}

	bn=$(basename "${old}" ".${type}")
	new="${dst}/${prefix}${bn}.${type}"

	if [ -e "${new}" ]; then 
		echo "Already exists: \"${new}\""
		continue
	fi
		
	echo "\"${old}\" -> \"${new}\""

	$convert "${old}" ${args} "${new}" || echo "^ ERROR"
done
