#!/bin/bash
# A quick and dirty thumbnailer which uses 'convert'to do the job. By gammy.

src=""
dst="thumbs"
prefix="thumb_"
size="100x100"

usage() {
	echo -e "Quick n dirty thumbnailer\n"
	echo "Usage: $(basename $0) -s <source path> [options]"
	echo -e "Example: $(basename $0) -p thumb_ -s 640x480 -p /originals/ -d ./thumbs/\n"
	echo "-s foo     set source path to 'foo'"
	echo "-d ${dst}  set destination path to '${dst}'"
	echo "-S ${size} set target size to ${size}"
	echo -e "-P ${prefix}  set target prefix to '${prefix}'\n"
	echo "Only the -s argument is required to run."
}

while getopts “s:d:S:P:h” opt; do
	case $opt in
		s)
			src="$OPTARG"
			;;
		d)
			dst="$OPTARG"
			;;
		S)
			size="$OPTARG"
			;;
		P)
			prefix="${OPTARG}"
			;;
		h)
			usage
			exit
			;;
	esac
done

if [ -z ${src} ]; then
	usage
	exit
fi

if [ ! -d ${dst} ]; then
	mkdir -v ${dst}
fi

find ${src} -maxdepth 1 -type f | while read old; do

	if [ $(file "${old}" | grep image | wc -l) != 1 ]; then
		continue # Skip non-images
	fi

	type=${old##*.}

	bn=$(basename "${old}" ".${type}")
	new="${dst}/${prefix}${bn}.${type}"

	if [ ! -e "${new}" ]; then # XXX might be nice to be able to override this
		echo "\"${old}\" -> \"${new}\""
		convert "${old}" \
			-scale ${size} \
			"${new}" || echo "^ ERROR"
	else
		echo "Already exists: \"${new}\""
	fi
done
