#!/bin/bash
# Use Yahoo Finance to convert currencies on the commandline
# This used to use xe.com (hence its name), but they've now blocked
# the web service from use without signing a EULA. So, byebye xe!
#
# The original idea was stolen from 
# http://www.commandlinefu.com/commands/view/7866/currency-converter-using-xe.com
# by gammy

for dep in curl bc sed; do
	which $dep > /dev/null || exit $?
done

if [ $# -lt 3 ]; then
	echo "Usage: xe <amount> <source currency> [in|to] <target currency>"
	echo "Example: xe 100+50 usd gbp"
	exit 1
fi

from="${2::3}" # Truncate to 3 chars

if [ "$3" == "in" -o "$3" == "to" ]; then
	to="${4::3}" 
else
	to="${3::3}" 
fi

args="s=${from}${to}=X&f=l1&e=.cs"
cmd="curl -s 'http://download.finance.yahoo.com/d/quotes.csv?${args}'"
rate=$(eval "$cmd")
code="$?"

if [ "$rate" == "N/A" ]; then
	echo "Unable to perform currency conversion" >&2
	exit 1
fi

# TODO: Assert that the result is a number 

if [ $code -ne 0 ]; then
	dump=$(mktemp)
	echo -e "$cmd: ($code)\n$rate" > "$dump"
	echo "It appears that conversion failed, see \"$dump\" for details" >&2
	exit $code
fi

amount=$(echo "$1" | bc -l)
xchange=$(echo "$amount * $rate" | bc -l)
echo "$amount $from = $xchange $to"
