#!/bin/bash
# Use the fixer.io web API to convert currencies on the commandline.
# This used to use Yahoo Finance and later xe.com (hence its name), 
# but they've now blocked their web services from use without signing a EULA,
# So, byebye xe and Yahoo Finance!
#
# The original idea was stolen from 
# http://www.commandlinefu.com/commands/view/7866/currency-converter-using-xe.com
# by gammy

for dep in curl bc sed; do
	which $dep > /dev/null || exit $?
done

if [ $# -lt 3 ]; then
	echo "Usage: xe <amount> <source currency> [in|to] <target currency>"
	echo "Example: xe 100+50 usd gbp"
	exit 1
fi

from="${2::3}" # Truncate to 3 chars

if [ "$3" == "in" -o "$3" == "to" ]; then
	to="${4::3}" 
else
	to="${3::3}" 
fi

cmd="curl -s 'https://api.fixer.io/latest?symbols=${from^^},${to^^}'"
response=$(eval "$cmd")
code_get="$?"
rate=$(eval "echo \"$response\" | sed -e 's/[{}:,]/ /g' | awk '{print \$NF}'")
code_rate="$?"

if [ $code_get -ne 0 -o \
     $code_rate -ne 0 ]; then
	dump=$(mktemp)
	echo -e "$cmd: ($code)\nResponse:\n$response\n\nRate:\n$rate\n" > "$dump"
	echo "It appears that conversion failed, see \"$dump\" for details" >&2
	exit $code
fi

amount=$(echo "$1" | bc -l)
xchange=$(echo "$amount * $rate" | bc -l)
echo "$amount $from = $xchange $to"
